/*Atividade 3

Crie um banco de dados para um serviço de farmácia de uma empresa, o nome do banco
deverá ter o seguinte nome db_farmacia_do_bem, onde o sistema trabalhará com as
informações dos produtos desta empresa.

O sistema trabalhará com 2 tabelas tb_produto e tb_categoria.

siga exatamente esse passo a passo:

Crie uma tabela de categorias utilizando a habilidade de abstração e determine 3 atributos
relevantes do tb_categoria para se trabalhar com o serviço desta farmacia.

Crie uma tabela de tb_produto e utilizando a habilidade de abstração e determine 5
atributos relevantes dos tb_produto para se trabalhar com o serviço deste farmacia(não
esqueça de criar a foreign key de tb_categoria nesta tabela).

Popule esta tabela Categoria com até 5 dados.

Popule esta tabela Produto com até 8 dados.

Faça um select que retorne os Produtos com o valor maior do que 50 reais.

Faça um select trazendo os Produtos com valor entre 3 e 60 reais.

Faça um select utilizando LIKE buscando os Produtos com a letra B.

Faça um um select com Inner join entre tabela categoria e produto.

Faça um select onde traga todos os Produtos de uma categoria específica (exemplo todos
os produtos que são cosméticos).*/

-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 11:48:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- drop database db_farmacia_do_bem; -- apagar banco
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem,
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem,
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem,` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem,` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem,`.`tb_categoria`
-- -----------------------------------------------------
select * from tb_categoria;
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem,`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NOT NULL,
  `precisa_receita` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

insert into  tb_categoria (categoria,precisa_receita)value ("Medicamentos","SIM");
insert into  tb_categoria (categoria,precisa_receita)value ("Beleza","NÃO");
insert into  tb_categoria (categoria,precisa_receita)value ("Cabelo","NÃO");
insert into  tb_categoria (categoria,precisa_receita)value ("Genéricos","SIM");
insert into  tb_categoria (categoria,precisa_receita)value ("Perfumaria","NÃO");
-- -----------------------------------------------------
-- Table `db_farmacia_do_bem,`.`tb_produto`
-- -----------------------------------------------------
 select * from tb_produto;
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem,`.`tb_produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(255) NOT NULL,
  `descrição` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(8,2) NOT NULL,
  `vencimento` DATE,
  `categoria_id` bigint,
    PRIMARY KEY (`id`),
      FOREIGN KEY (`categoria_id`)  REFERENCES `tb_categoria`(`id`)
);

insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("ATENOLOL 25MG","indicado para o tratamento da esquizofrenia",69.90,"2022-08-10",1);
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("HEMIFUMARATO DE QUETIAPINA 25MG","O atenolol é indicado para o controle da hipertensão arterial (pressão alta)",33.80,"2022-10-21",1);
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("MÁSCARA PARA CÍLIOS","Alta duração com preenchimento equilibrado, não deixando gomos no cílios",04.99,"2022-10-21",2);
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("PÓ COMPACTO SUNLESS","Indicado para todos os tipo de pele",90.99,"2023-09-09",2); -- ok
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("CREME SELANTE","O creme selante termoativado garante proteção aos fios",12.80,"2024-10-21",3);
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("TINTURA IMEDIA CASTANHO","Sua tecnologia avançada protege e cuida dos cabelos antes, durante e depois da coloração",29.90,"2022-04-01",3); -- ok 
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("PARACETAMOL 750MG","Indicado para dor (analgésico) e febre (antitérmico)",03.01,"2023-06-24",4);
insert into  tb_produto (nome_produto,descrição,valor,vencimento,categoria_id)
value ("REXONA CLINICAL FEMININO","Protege 3x mais contra a transpiração excessiva que um antitranspirante comum",16.80,"2022-10-21",5);


 select * from tb_produto;
select * from tb_produto where valor > 50;
select * from tb_produto where valor > 3 and valor < 60;
select * from tb_produto inner join tb_categoria on
tb_produto.categoria_id = tb_categoria.id;
select * from tb_produto  where nome_produto like "%c%"; -- troquei a letra por C (não peguei exemplos com B)
select * from tb_produto inner join tb_categoria
on  tb_categoria.id =1 = tb_produto.categoria_id ;

